### ISSUE TITLE
自定义变量？

### ISSUE THREAD

**Issue by liuzj288** [Special-Week/nonebot_plugin_impact#1]
比如cd时间啥的能设置吗

**Comment by Special-Week** [comment]
目前没通过读取env拿数据, 你可以通过修改源码改数字, 单位是秒, 就在utils.py那里, 晚点有时间我再加

**Comment by liuzj288** [comment]
> 目前没通过读取env拿数据, 你可以通过修改源码改数字, 单位是秒, 就在utils.py那里, 晚点有时间我再加

重启后报错了，路径出了问题
![image](https://user-images.githubusercontent.com/13833404/215403240-ea1e0e9e-5f0d-48fb-b6c4-f41ece0a4c20.png)

**Comment by Special-Week** [comment]
你怎么把我写的路径data的d给删了....我的意思是让你把utils.py最下面几行的cd时间变量改一下

**Comment by Special-Week** [comment]
> 你怎么把我写的路径data的d给删了....我的意思是让你把utils.py最下面几行的cd时间变量改一下

我应该有注释的

**Comment by liuzj288** [comment]
> > 目前没通过读取env拿数据, 你可以通过修改源码改数字, 单位是秒, 就在utils.py那里, 晚点有时间我再加
> 
> 重启后报错了，路径出了问题 ![image](https://user-images.githubusercontent.com/13833404/215403240-ea1e0e9e-5f0d-48fb-b6c4-f41ece0a4c20.png)

你少打了个字母d


> > 你怎么把我写的路径data的d给删了....我的意思是让你把utils.py最下面几行的cd时间变量改一下
> 
你代码漏了d
![image](https://user-images.githubusercontent.com/13833404/215403605-a816dc9f-9ab9-40ac-9d37-8dc0a804baff.png)

**Comment by Special-Week** [comment]
好吧我的锅, cv的时候少了一个字符

**Comment by liuzj288** [comment]
> 好吧我的锅, cv的时候少了一个字符

建议
1.pk概率能不能根据长度差值分别调整概率，比如长度差越大概率越大；
2.长度跌到一定值或者到达一定值可以触发彩蛋；
