### ISSUE TITLE
插件加载进去了 但没反应

### ISSUE THREAD

**Issue by 1103859909** [Special-Week/nonebot_plugin_impact#13]
![RGXQHTR6ERKPYZV7QN} 95H](https://user-images.githubusercontent.com/107859647/216820166-ba562704-8192-41a0-9ab9-2acc06335b0c.png)
![OBIPJDL7E`GRB$T~OPQ~)U](https://user-images.githubusercontent.com/107859647/216820167-43fda673-dc1e-43f3-966f-5ceacfd3e6bf.png)
![NRP$XK (7K~YQWZ8H}41QL](https://user-images.githubusercontent.com/107859647/216820171-36f53fe3-345e-45e1-a7cb-18921d7ae0bf.png)
![OVV53 V%SIJ$X5DRKC 1EEP](https://user-images.githubusercontent.com/107859647/216820173-20e41ca6-fc9b-4192-8660-ee02a926c9df.png)

**Comment by Special-Week** [comment]
on_command响应器需要加命令头(COMMAND_START)[https://v2.nonebot.dev/docs/api/config#Config-command_start] 
而且使用该指令需要superusers账号

**Comment by 1103859909** [comment]
![image](https://user-images.githubusercontent.com/107859647/216820727-edbc5237-728a-46be-a459-6e10c027532b.png)
有的

**Comment by Special-Week** [comment]
在群聊中使用指令

**Comment by 1103859909** [comment]
![image](https://user-images.githubusercontent.com/107859647/216820985-55dd5352-0dad-41b9-a800-7fd51548f278.png)
mei'f没反应

**Comment by 1103859909** [comment]
> 

这两个搞得其他插件是有反应的

**Comment by 1103859909** [comment]
> on_command响应器需要加命令头(COMMAND_START)[https://v2.nonebot.dev/docs/api/config#Config-command_start] 而且使用该指令需要superusers账号

这两个搞得其他插件是有反应的

**Comment by Special-Week** [comment]
被你plugin目录下的mute插件阻断了

**Comment by 1103859909** [comment]
是插件冲突的意思吗

**Comment by Special-Week** [comment]
我填的响应器优先级是20, 可能有插件填的priority优先级更高匹配到了命令且block=true
自己加载单个插件试试看, 有用可以尝试手动对源码进行priority修改提权

**Comment by 1103859909** [comment]
嗯嗯可以了 谢谢大佬  是这个问题（爱心
）

> 我填的响应器优先级是20, 可能有插件填的priority优先级更高匹配到了命令且block=true 自己加载单个插件试试看, 有用可以尝试手动对源码进行priority修改提权
