### ISSUE TITLE
on_command全部没反应, on_regex正常

### ISSUE THREAD

**Issue by Laurc2004** [Special-Week/nonebot_plugin_impact#17]
![image](https://user-images.githubusercontent.com/119660750/221413804-25e61274-4de3-4c2d-a885-e38b549ef7eb.png)
嗦牛子、pk等不能用
打胶、日群友等功能能用

**Comment by Special-Week** [comment]
使用on_command的响应器, 指令需要带上自己env的COMMAND_START, 默认为"/"

**Comment by Laurc2004** [comment]
您好，麻烦问下怎么可以不用带"/"，我这样设置报错了，小白求教
![image](https://user-images.githubusercontent.com/119660750/221416172-c45b24fb-b4d5-46cb-88c5-bd10e442dadb.png)

**Comment by Special-Week** [comment]
COMMAND_START = [""]

**Comment by Laurc2004** [comment]
已解决，感谢您的回复速度。
