### ISSUE TITLE
无法开启淫趴

### ISSUE THREAD

**Issue by CaffuChin0** [Special-Week/nonebot_plugin_impact#18]
其他功能都正常，只有输入开启淫趴没有任何反应
![QQ截图20230302133648](https://user-images.githubusercontent.com/47897127/222341247-d1190a58-ec0a-4614-9970-4f95051d15de.png)
![QQ截图20230302133701](https://user-images.githubusercontent.com/47897127/222341252-51682773-54cf-4613-b892-1e45f9a83662.png)
![QQ截图20230302133945](https://user-images.githubusercontent.com/47897127/222341257-6e936ac0-cf19-463c-ab77-d5c3ca278b77.png)

**Comment by Special-Week** [comment]
superuser，群管理，群主这三种身份才有效，而且必须在群里

**Comment by CaffuChin0** [comment]
> superuser，群管理，群主这三种身份才有效，而且必须在群里

是superuser也是群主

**Comment by Special-Week** [comment]
控制台输出呢

**Comment by CaffuChin0** [comment]
> 控制台输出呢

请问一下是不是blackword的问题？priority越大优先级越大还是相反？
![2](https://user-images.githubusercontent.com/47897127/222342441-87bf9224-15d6-4a61-ac16-aaa015650e31.png)

![1](https://user-images.githubusercontent.com/47897127/222342389-8398870b-6710-4577-afd3-0f3d096e3981.png)

**Comment by Special-Week** [comment]
那可能是被阻断了，priority越低优先级越高，你把开启淫趴的响应器改一下优先级吧

**Comment by CaffuChin0** [comment]
> 那可能是被阻断了，priority越低优先级越高，你把开启淫趴的响应器改一下优先级吧

没问题了！谢谢！感谢您这么迅速的回复速度！
