### ISSUE TITLE
指令触发条件不够严格，没有退出该玩法的指令

### ISSUE THREAD

**Issue by untitledunrevised** [Special-Week/nonebot_plugin_impact#21]
聊天记录的内容如下：

> 我：「查询谱师的精神状态」
> Hinata：「@Untitled_unrevised 你还没有创建JJ喵, 咱帮你创建了喵, 目前长度是10cm喵」

具体来说，我非常反感的几个问题是：
1. 只要是以「查询」为开头的，都会触发该指令；这很容易引发误判；
2. 触发指令后，发现没有数据就会自动创建；把这条和 1. 结合起来是非常恶心的；
3. 出现问题了，应该立刻删除数据；但是我没有看到可以删除自己数据并退出的指令；

**Comment by Special-Week** [comment]
你觉得怎么匹配比较好，建议自己改响应器
