### ISSUE TITLE
[建议] 注释不是越多越好

### ISSUE THREAD

**Issue by CAESIUS-TIM** [Special-Week/nonebot_plugin_impact#26]
https://github.com/Special-Week/nonebot_plugin_impact/blob/99758850e81b2cc76b594f9bd01efe0318dce039/nonebot_plugin_impact/handle.py#L28

不需要疯狂加注释。使用合适的变量名，简洁的代码结构，来提高代码自身的可读性，看代码就能知道功能更为重要。而且代码更改而注释忘改反而可能会导致错误。

比如这里就可以使用 type hint：

```python
uid: str = event.get_user_id()
```

**Comment by Special-Week** [comment]
好的
