### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by PackageInstaller** [Special-Week/nonebot_plugin_impact#27]
![image](https://github.com/Special-Week/nonebot_plugin_impact/assets/80018096/1bbf9bb5-0ef8-4b20-bd61-22bb96e3b923)

如图，所有功能都用不了了
Bot：zhenxun_bot
os：Arch linux
nonebot版本：2.0.0rc4
python版本：3.11.3

**Comment by Special-Week** [comment]
已经做好了适配, 版本号为0.0.9

**Comment by Bearlele** [comment]
“日群主”“开启银趴”等命令无法使用，错误 KeyError: '_matched_groups'
插件版本应该是 0.12.114514（？）
![image](https://github.com/user-attachments/assets/0381a56b-22d4-4936-8f5d-cafb954974cb)

**Comment by Special-Week** [comment]
> “日群主”“开启银趴”等命令无法使用，错误 KeyError: '_matched_groups' os: debian11 nonebot: 2.0.1 插件版本应该是 0.12.114514（？） ![image](https://private-user-images.githubusercontent.com/30120610/354874036-0381a56b-22d4-4936-8f5d-cafb954974cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDUyNjEsIm5iZiI6MTcyMjc0NDk2MSwicGF0aCI6Ii8zMDEyMDYxMC8zNTQ4NzQwMzYtMDM4MWE1NmItMjJkNC00OTM2LThmNWQtY2FmYjk1NDk3NGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA0MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzFkYjk0MDQ3ZTk4NjIzODVhNzhhMjUwZDgyYzgxYjlkNzU4OGQzNGQzMDQ1ZjI2NmI5NDFkMTI2OTk2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJiMC7xrkl6c0bEsp5O9vWpXAAUMJ5MJA4GSPOW9pYs)

这个问题我早在Jun 20, 2023 就已经做了适配，你肯定是没更新
![image](https://github.com/user-attachments/assets/d7381690-d1e4-4faf-b8b6-f195ac86ba35)

**Comment by Bearlele** [comment]
www我看看，我还以为用nb安装直接就是最新版

**Comment by Bearlele** [comment]
> > “日群主”“开启银趴”等命令无法使用，错误 KeyError: '_matched_groups' os: debian11 nonebot: 2.0.1 插件版本应该是 0.12.114514（？） ![image](https://private-user-images.githubusercontent.com/30120610/354874036-0381a56b-22d4-4936-8f5d-cafb954974cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDUyNjEsIm5iZiI6MTcyMjc0NDk2MSwicGF0aCI6Ii8zMDEyMDYxMC8zNTQ4NzQwMzYtMDM4MWE1NmItMjJkNC00OTM2LThmNWQtY2FmYjk1NDk3NGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA0MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NzFkYjk0MDQ3ZTk4NjIzODVhNzhhMjUwZDgyYzgxYjlkNzU4OGQzNGQzMDQ1ZjI2NmI5NDFkMTI2OTk2YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GJiMC7xrkl6c0bEsp5O9vWpXAAUMJ5MJA4GSPOW9pYs)
> 
> 这个问题我早在Jun 20, 2023 就已经做了适配，你肯定是没更新 ![image](https://private-user-images.githubusercontent.com/87489040/354875215-d7381690-d1e4-4faf-b8b6-f195ac86ba35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDUzMTUsIm5iZiI6MTcyMjc0NTAxNSwicGF0aCI6Ii84NzQ4OTA0MC8zNTQ4NzUyMTUtZDczODE2OTAtZDFlNC00ZmFmLWI4YjYtZjE5NWFjODZiYTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA0MTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZmFhODdlYTA0NjczZDlmZDllNmFhZGYyN2ExOWNlZDRhNGM1ZTZjYmJjMTMyMDMxZWY0YWZjY2NmNTFiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g8BZDGt8tjYmNdsqjTcNEos5jB9Zr1mI9nph3LKJlog)

www我看看，我还以为用nb安装直接就是最新版
