### ISSUE TITLE
运行时报错 not “int”

### ISSUE THREAD

**Issue by HggDemo** [Special-Week/nonebot_plugin_impact#3]

**Comment by HggDemo** [comment]
![image](https://user-images.githubusercontent.com/52238701/215723172-a1c07df4-50d9-40c8-8872-e8c5d35e8f33.png)

**Comment by Special-Week** [comment]
能否提供具体的log

**Comment by HggDemo** [comment]
奥 是我犯错了，我复制忘记加注释了
![image](https://user-images.githubusercontent.com/52238701/215724536-23d10e2a-89ff-40cb-aba5-fa7766883677.png)
运行没问题，西西
