### ISSUE TITLE
希望新增配置项

### ISSUE THREAD

**Issue by dong2005923** [Special-Week/nonebot_plugin_impact#34]
你好，能否添加下分群开关的配置或增加绝对权限。
例如只能超级用户开启，例如增加配置项来管理开关
有些群友觉得刷屏不想玩，但是群主or管理员又将其打开

**Comment by Special-Week** [comment]
那你这个有点难管，推荐你还是按照自己喜好改一下插件源码，这个插件响应器部分全在__init__.py这下面，这里面有一段这样的代码
```python
on_regex(
    r"^(开始银趴|关闭银趴|开启淫趴|禁止淫趴|开启银趴|禁止银趴)",
    permission=SUPERUSER | GROUP_ADMIN | GROUP_OWNER,
    flags=I,
    priority=20,
    block=True,
    handlers=[impart.open_module],
)
```
你把其中的
```permission=SUPERUSER | GROUP_ADMIN | GROUP_OWNER
```
改成
```
permission=SUPERUSER
```
就只能超级用户开关了

**Comment by dong2005923** [comment]
> 那你这个有点难管，推荐你还是按照自己喜好改一下插件源码，这个插件响应器部分全在__init__.py这下面，这里面有一段这样的代码
> 
> ```python
> on_regex(
>     r"^(开始银趴|关闭银趴|开启淫趴|禁止淫趴|开启银趴|禁止银趴)",
>     permission=SUPERUSER | GROUP_ADMIN | GROUP_OWNER,
>     flags=I,
>     priority=20,
>     block=True,
>     handlers=[impart.open_module],
> )
> ```
> 
> 你把其中的
> 
> ```
> permission=SUPERUSER | GROUP_ADMIN | GROUP_OWNER
> ```
> 
> 改成
> 
> ```
> permission=SUPERUSER
> ```
> 
> 就只能超级用户开关了

好的，谢谢
