### ISSUE TITLE
BUG，json版换数据库版后，统计过万就报错

### ISSUE THREAD

**Issue by xh22805** [Special-Week/nonebot_plugin_impact#35]
'raw_command': '注入查询', 'command_arg': [MessageSegment(type='text', data={'text': '全部'}), M...
          │    │          │    └ GroupMessageEvent(time=1692262277, self_id=3141812259, post_type='message', sub_type='normal', user_id=3214630571, message_ty...
          │    │          └ Bot(type='OneBot V11', self_id='3141812259')
          │    └ <function Matcher.simple_run at 0x7fee7cf095a0>
          └ Matcher(type='message', module=extensive_plugin.Yl.ypa)
  File "/yl/CQ/CQ1/zx/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 734, in simple_run
    await handler(
          └ Dependent(call=query_injection)
  File "/yl/CQ/CQ1/zx/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'matcher': Matcher(type='message', module=extensive_plugin.Yl.ypa), 'event': GroupMessageEvent(time=1692262277, self_id=3141...
                 │    │             │         │    │    └ <function Impart.query_injection at 0x7fee58c94af0>
                 │    │             │         │    └ Dependent(call=query_injection)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7fee7e129e10>

  File "/yl/CQ/CQ1/zx/extensive_plugin/Yl/ypa/handle.py", line 403, in query_injection
    await draw_bar_chart.draw_line_chart(inject_data)
          │              │               └ {'2023-05-06': 396.048, '2023-05-07': 604.331, '2023-05-08': 617.416, '2023-05-09': 156.646, '2023-05-10': 1038.044, '2023-05...
          │              └ <function DrawBarChart.draw_line_chart at 0x7fee58c07ac0>
          └ <extensive_plugin.Yl.ypa.draw_img.DrawBarChart object at 0x7fee58c50040>

  File "/yl/CQ/CQ1/zx/extensive_plugin/Yl/ypa/draw_img.py", line 230, in draw_line_chart
    f"{keys[i]}   {values[i]}ml",

IndexError: list index out of range

**Comment by Special-Week** [comment]
已修复, 更新一下
