### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by XibieTime** [Special-Week/nonebot_plugin_impact#36]
日群友以后输出的两个名片都是发起人的 
好欸！白苏(24916****)用时2秒 
给 白苏(49776****) 注入了8.419毫升的脱氧核糖核酸, 当日总注入量为：8.419毫升
就像这样··第二个名片本应该是幸运群友的

**Comment by Special-Week** [comment]
你是不是at了自己

**Comment by Special-Week** [comment]
如果后面有at的话, 目标直接指向的被at的人

**Comment by Special-Week** [comment]
你这边一直没回复, 而我确实有意让存在at就把对象指向被at的人, 我这边就close掉了

**Comment by Special-Week** [comment]
已修
