### ISSUE TITLE
貌似有个bug

### ISSUE THREAD

**Issue by aknyzsd** [Special-Week/nonebot_plugin_impact#37]
最近发现bot收到长消息会莫名奇妙的卡死，寻找原因发现了类似问题如下
https://github.com/kexue-z/nonebot-plugin-heweather/issues/46
然后发现咱这个插件里也有读取消息进行正则判定的码（不确定是不是本插件导致的，缝了一堆）
佬看下这个需不需要改

**Comment by Special-Week** [comment]
按道理我这边正则写的这么简单应该不会遇到什么性能问题，嘛...那我抽空把正则换成其他响应器吧

**Comment by aknyzsd** [comment]
问题解决，另外一个插件导致的，打扰了
