### ISSUE TITLE
排行榜报错，其他功能正常

### ISSUE THREAD

**Issue by HggDemo** [Special-Week/nonebot_plugin_impact#4]
![image](https://user-images.githubusercontent.com/52238701/215736355-321c506f-9a49-434e-b4ee-1a4c41e3e523.png)
只修改过触发的关键字

**Comment by Special-Week** [comment]
这个是输出图片的形式发送的, 我猜测你的Linux没有simsun.ttc(宋体)这个字体

**Comment by Special-Week** [comment]
解决方案: 源码内txtToImg.py中函数txt_to_img第三个参数font_path的值, 换成你系统有的字体, 或者安装simsun.ttc这个字体

**Comment by HggDemo** [comment]
![image](https://user-images.githubusercontent.com/52238701/215740810-b6965990-7ff1-4e32-bb92-161e0fc28c40.png)
gao'ding搞定咯，蟹蟹，直接下载了一个字体❤

**Comment by Umamusume-Agnes-Digital** [comment]
在已有simsun.ttc字体的情况下，无法生成图片
![image](https://user-images.githubusercontent.com/70925546/216207039-2fc20019-6ae4-4fad-a33d-ea18db84e9f4.png)
![image](https://user-images.githubusercontent.com/70925546/216207122-8f8e53d9-3c09-45ae-a520-df4cddc71e94.png)

**Comment by Special-Week** [comment]
> 在已有simsun.ttc字体的情况下，无法生成图片 ![image](https://user-images.githubusercontent.com/70925546/216207039-2fc20019-6ae4-4fad-a33d-ea18db84e9f4.png) ![image](https://user-images.githubusercontent.com/70925546/216207122-8f8e53d9-3c09-45ae-a520-df4cddc71e94.png)

cannot open resource
试着参考一下上面的解决方案?下一个字体到bot目录
